app:
  labels:
    # Make stack a global service
    io.rancher.scheduler.global: 'true'
    # Make stack only run containers on hosts with a app=label
    io.rancher.scheduler.affinity:host_label: ${APP_LABEL}=true
    traefik.enable: ${APP_LB}
    traefik.domain: ${APP_DOMAIN}
    traefik.port: ${APP_PORT}
  environment:
    APP_VERSION: ${APP_VERSION}
    APP_LABEL: ${APP_LABEL}
    SITE_REPO: ${SITE_REPO}
    SITE_BRANCH: ${SITE_BRANCH}
    STARTUP_SCRIPT: ${STARTUP_SCRIPT}
    ENV: ${APP_ENV}
    DATABASE_NAME: ${DATABASE_NAME}
    DATABASE_USER: ${DATABASE_USER}
    DATABASE_PASSWORD: ${DATABASE_PASSWORD}
    SYMFONY__ENV: ${APP_ENV}
    SYMFONY__DATABASE__NAME: ${DATABASE_NAME}
    SYMFONY__DATABASE__USER: ${DATABASE_USER}
    SYMFONY__DATABASE__PASSWORD: ${DATABASE_PASSWORD}
  image: "wd29/php:${APP_VERSION}"
  ports:
    - "22"