app:
  labels:
    # Make stack a global service
    io.rancher.scheduler.global: 'true'
    # Make stack only run containers on hosts with a app=label
    io.rancher.scheduler.affinity:host_label: ${APP_LABEL}=true
  environment:
    APP_VERSION: ${APP_VERSION}
    APP_LABEL: ${APP_LABEL}
    SITE_REPO: ${SITE_REPO}
    SITE_BRANCH: ${SITE_BRANCH}
    STARTUP_SCRIPT: ${STARTUP_SCRIPT}
    APP_ENV: ${APP_ENV}
    APP_DATABASE_NAME: ${APP_DATABASE_NAME}
    APP_DATABASE_USER: ${APP_DATABASE_USER}
    APP_DATABASE_PASSWORD: ${APP_DATABASE_PASSWORD}
    SYMFONY__ENV: ${APP_ENV}
    SYMFONY__DATABASE__NAME: ${APP_DATABASE_NAME}
    SYMFONY__DATABASE__USER: ${APP_DATABASE_USER}
    SYMFONY__DATABASE__PASSWORD: ${APP_DATABASE_PASSWORD}
  image: "wd29/php:${APP_VERSION}"
  ports:
    - "22"
    - "80"
    - "443"