.catalog:
  name: "WD29 PHP 7/hhvm Box"
  version: 1.0
  description: |
    Application PHP Scalable
  questions:
    - variable: "APP_VERSION"
      default: "v2.1"
      type: string
      required: true
      label: "Version à déployer"
      description: "Version de l'image à pull sur Docker-hub"
    - variable: "EMAIL"
      default: "ben@webdesign29.net"
      type: string
      required: true
      label: "Your email"
      description: "Used in lets's encrypt certification process"
    - variable: "URL"
      default: "myapp.domain.com"
      type: string
      required: true
      label: "Domain name"
      description: "Domain name that should be registered in Traefik and Certification"
    - variable: "SUBDOMAINS"
      default: "www,api,dev,re7"
      type: string
      required: true
      label: "Sub domains"
      description: "Sub domains up for certification"
    - variable: "APP_LB"
      default: "true"
      type: string
      required: true
      label: "Use Traefik ?"
      description: "Enables Traefik Load Balancing"
    - variable: "APP_PORT"
      default: "80"
      type: string
      required: true
      label: "Port"
      description: "Port that traefik should route to"
    - variable: "APP_LABEL"
      default: "prod"
      type: string
      required: true
      label: "Tag du host pour déploiement selectif"
      description: "Cette variable sera utilisé pour déployer uniquement sur les hosts taggé avec APP_LABEL=true"
    - variable: "DATABASE_NAME"
      default: "prod"
      type: string
      required: true
      label: "DATABASE_NAME"
      description: "Nom de la base de donnée MySQL"
    - variable: "DATABASE_USER"
      default: "db_usr"
      type: string
      required: true
      label: "DATABASE_USER"
      description: "Nom de l'utilisateur MySQL"
    - variable: "DATABASE_PASSWORD"
      type: string
      required: true
      label: "DATABASE_PASSWORD"
      description: "Mot de passe de l'utilisateur MySQL"
    - variable: "APP_ENV"
      default: prod
      type: string
      required: true
      label: "ENV"
      description: "Généralement 'dev' ou 'prod'"
    - variable: "SITE_REPO"
      type: string
      required: false
      label: "Git clone url"
      description: 'Url du dépot à clonner (doit être "pullable" grâce à une clée privée ou publique), Privée de la forme : git@... '
    - variable: "SITE_BRANCH"
      default: master
      type: string
      required: true
      label: "La branche à clonner dans la box"
      description: "Permet de sélectionner une branche spécifique pour le déploiement"
    - variable: "HEALTH_CHEK_URL"
      default: "/"
      type: string
      required: true
      label: "Healthcheck url path"
      description: "Healthcheck URL"
    - variable: "HEALTH_CHEK_TIMEOUT"
      default: 4000
      type: string
      required: true
      label: "Timeout"
      description: "Timeout between checks"

app:
  health_check:
    port: 80
    interval: 3000
    request_line: GET ${HEALTH_CHEK_URL} HTTP/1.0
    unhealthy_threshold: 3
    healthy_threshold: 2
    response_timeout: ${HEALTH_CHEK_TIMEOUT}