.catalog:
  name: "WD29 PHP 7/hhvm Box"
  version: 1.1
  description: |
    Application PHP Scalable
  questions:
    - variable: "APP_VERSION"
      default: "v65"
      type: string
      required: true
      label: "Version de l'image à pull sur Docker-hub"
      description: "Version à déployer"
    - variable: "APP_INDEX_FILE"
      default: "app.php"
      type: string
      required: true
      label: "Fichier index"
      description: "Fichier à utiliser comme index.php par nginx"
    - variable: "APP_LABEL"
      default: "prod"
      type: string
      required: true
      label: "Tag du host pour déploiement selectif"
      description: "Cette variable sera utilisé pour déployer uniquement sur les hosts taggé avec app=variable"
    - variable: "STARTUP_SCRIPT"
      default: "boot_app.sh"
      type: string
      required: true
      label: "App Startup - Bash script"
      description: "Script de build executable lors du post provisionement de la machine"
    - variable: "DATABASE_NAME"
      default: "prod"
      type: string
      required: true
      label: "DATABASE_NAME"
      description: "Nom de la base de donnée MySQL"
    - variable: "DATABASE_USER"
      default: "db_usr"
      type: string
      required: true
      label: "DATABASE_USER"
      description: "Nom de l'utilisateur MySQL"
    - variable: "DATABASE_PASSWORD"
      type: string
      required: true
      label: "DATABASE_PASSWORD"
      description: "Mot de passe de l'utilisateur MySQL"
    - variable: "APP_ENV"
      default: prod
      type: string
      required: true
      label: "ENV"
      description: "Généralement 'dev' ou 'prod'"
    - variable: "SITE_REPO"
      type: string
      required: false
      label: "Git clone url"
      description: 'Url du dépot à clonner (doit être "pullable" grâce à une clée privée ou publique), Privée de la forme : git@... '
    - variable: "SITE_BRANCH"
      default: master
      type: string
      required: true
      label: "La branche à clonner dans la box"
      description: "Permet de sélectionner une branche spécifique pour le déploiement"

app:
  health_check:
    port: 80
    interval: 3000
    request_line: GET /healthcheck HTTP/1.0
    unhealthy_threshold: 3
    healthy_threshold: 2
    response_timeout: 4000