goaleo-app: 
  environment:
    ROOT_PASS: "${ROOT_PASS}"
    SITE_REPO: "${SITE_REPO}"
    APP_ENV: "${APP_ENV}"
    DATABASE_NAME: "${DATABASE_NAME}"
    DATABASE_USER: "${DATABASE_USER}"
    DATABASE_PASSWORD: "${DATABASE_PASSWORD}"
  image: "wd29/goaleo:${APP_VERSION}"
  external_links:
    - "${DATABASE_HOST}":db
    - "${ES_HOST}":es
  ports:
    - "22"

goaleo-app-lb:
  expose:
  - 80:80
  - 443:443
  tty: true
  image: rancher/load-balancer-service
  links:
  - goaleo-app:goaleo-app
  stdin_open: true