goaleo-app: 
  environment:
    ROOT_PASS: "${root_pass}"
    APP_ENV: "${app_env}"
  image: "wd29/goaleo"
  external_links:
    - galera/galera:db
    - elasticsearch/elasticsearch-clients:es
  ports:
    - "22"

goaleo-app-lb:
  expose:
  - 80:80
  - 443:443
  tty: true
  image: rancher/load-balancer-service
  links:
  - goaleo-app:goaleo-app
  stdin_open: true