.catalog:
  name: "Goaleo"
  version: 1.1.0
  description: |
    Application Goaleo
  questions:
    - variable: "APP_VERSION"
      default: "v1.1.1"
      type: string
      required: true
      label: "Version de l'image à pull sur Docker-hub"
      description: "Version à déployer"
    - variable: "LB_LABEL"
      default: "prod"
      type: string
      required: true
      label: "Tag du host pour déploiement selectif"
      description: "Cette variable sera utilisé pour déployer uniquement sur les hosts taggé avec app=variable"
    - variable: "DATABASE_NAME"
      default: "prod_goaleo"
      type: string
      required: true
      label: "SYMFONY__DATABASE__NAME"
      description: "Nom de la base de donnée MySQL"
    - variable: "DATABASE_USER"
      default: "goaleo_usr"
      type: string
      required: true
      label: "SYMFONY__DATABASE_USER"
      description: "Nom de l'utilisateur MySQL"
    - variable: "DATABASE_PASSWORD"
      type: string
      required: true
      label: "SYMFONY__DATABASE_PASSWORD"
      description: "Mot de passe de l'utilisateur MySQL"
    - variable: "ROOT_PASS"
      type: string
      required: true
      label: "Mot de passe root pour connexion ssh"
      description: "Veuillez tapper un mot de passe compliqué supérieur à 15 caractères"
    - variable: "APP_ENV"
      default: prod
      type: string
      required: true
      label: "SYMFONY__ENV"
      description: "Généralement 'dev' ou 'prod'"
    - variable: "SITE_REPO"
      default: git@bitbucket.org:GoaleoTeam/goaleo.git
      type: string
      required: true
      label: "Git clone url"
      description: 'Url du dépot à clonner (doit être "pullable" grâce à une clée privée ou publique), Privée de la forme : git@... '
    - variable: "SITE_BRANCH"
      default: cloudify
      type: string
      required: true
      label: "La branche à clonner dans la box"
      description: "Permet de sélectionner une branche spécifique pour le déploiement"

goaleo:
  scale: 1
goaleo-lb:
  scale: 1
  load_balancer_config: {}
  health_check:
    port: 80
    interval: 3000
    unhealthy_threshold: 3
    healthy_threshold: 2
    response_timeout: 3000