.catalog:
  name: "WordPress"
  version: 1.0.1
  description: |
    WordPress PHP7
  questions:
    - variable: "APP_VERSION"
      default: "latest"
      type: string
      required: true
      label: "Version de l'image à pull sur Docker-hub"
      description: "Version à déployer"
    - variable: "APP_LABEL"
      default: "prod"
      type: string
      required: true
      label: "Tag du host pour déploiement selectif"
      description: "Cette variable sera utilisé pour déployer uniquement sur les hosts taggé avec app=variable"
    - variable: "ROOT_PASS"
      type: string
      required: true
      label: "Mot de passe root pour connexion ssh"
      description: "Veuillez tapper un mot de passe compliqué supérieur à 15 caractères"
    - variable: "DATABASE_NAME"
      default: "db_name"
      type: string
      required: true
      label: "DATABASE_NAME"
      description: "Nom de la base de donnée MySQL"
    - variable: "DATABASE_USER"
      default: "db_usr"
      type: string
      required: true
      label: "DATABASE_USER"
      description: "Nom de l'utilisateur MySQL"
    - variable: "db_pass"
      type: string
      required: true
      label: "DATABASE_PASSWORD"
      description: "Mot de passe de l'utilisateur MySQL"
    - variable: "APP_ENV"
      default: dev
      type: string
      required: true
      label: "APP_ENV"
      description: "Généralement 'dev' ou 'prod'"
goaleo:
  scale: 1
  health_check:
    port: 80
    interval: 3000
    unhealthy_threshold: 3
    healthy_threshold: 2
    response_timeout: 3000
  